sudo: required
services:
  - docker

before_install:
  - docker build -t ermannb/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ermannb/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker"
  environment: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-018991611705"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
